# Generated by Django 3.2.13 on 2022-05-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0002_post_subtitulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitulo',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
