# Generated by Django 3.2.13 on 2022-04-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoluna', '0002_alter_duenio_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duenio',
            name='dni',
            field=models.IntegerField(verbose_name='DNI'),
        ),
    ]
