# Generated by Django 3.2.13 on 2022-05-10 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoluna', '0003_alter_duenio_dni'),
    ]

    operations = [
        migrations.DeleteModel(
            name='atencion',
        ),
        migrations.DeleteModel(
            name='duenio',
        ),
        migrations.DeleteModel(
            name='mascota',
        ),
        migrations.DeleteModel(
            name='veterinario',
        ),
    ]
