# Generated by Django 3.2.13 on 2022-04-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('fecha_nac', models.DateTimeField()),
                ('tipo', models.CharField(max_length=40)),
                ('raza', models.CharField(max_length=40)),
            ],
        ),
    ]
