# Generated by Django 3.2.13 on 2022-04-25 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAtenciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mascota',
            new_name='mascotas',
        ),
    ]
