# Generated by Django 3.2.13 on 2022-05-10 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAtenciones', '0003_atenciones_duenios_veterinarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='atenciones',
        ),
        migrations.DeleteModel(
            name='duenios',
        ),
        migrations.DeleteModel(
            name='mascotas',
        ),
        migrations.DeleteModel(
            name='veterinarios',
        ),
    ]
