# Generated by Django 3.2.13 on 2022-05-10 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAdopciones', '0002_alter_pet_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'verbose_name': 'Adopcion', 'verbose_name_plural': 'Adopciones'},
        ),
    ]
