# Generated by Django 3.2.13 on 2022-05-14 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAdopciones', '0003_alter_pet_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'verbose_name': 'Pet', 'verbose_name_plural': 'Pets'},
        ),
    ]
