# Generated by Django 3.2.13 on 2022-05-15 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdopciones', '0005_alter_pet_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='tipo',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
