# Generated by Django 3.2.13 on 2022-05-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdopciones', '0007_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='tipos',
            field=models.ManyToManyField(to='appAdopciones.Tipo'),
        ),
    ]
